site_name: FastAPI Redis Cache (Reborn!)

theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - toc.follow
    # - navigation.expand

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay-dev

copyright: © 2024 Grant Ramsay (Seapagan)

plugins:
  - mkdocstrings
  - search
  - latest-git-tag
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

repo_url: https://github.com/seapagan/fastapi-redis-cache-reborn
repo_name: fastapi-redis-cache-reborn

dev_addr: "127.0.0.1:9000"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      linenums: false
      auto_title: false
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage: usage.md
  - To Do: todo.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
