name: Type Checking

on: [push, pull_request, workflow_dispatch]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: ""
          mypy_flags: "--config-file pyproject.toml"
